# Generated by Django 5.1.3 on 2024-12-11 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelinvoice',
            name='disel_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='fuelinvoice',
            name='euro_3_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='fuelinvoice',
            name='petrol_92_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='fuelinvoice',
            name='petrol_95_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='fuelinvoice',
            name='super_disel_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='fuelinvoice',
            name='x_mile_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
