# Generated by Django 5.1.3 on 2024-12-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_invoice', '0002_alter_fuelinvoice_disel_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelinvoice',
            name='related_month',
            field=models.IntegerField(default=12, max_length=100),
        ),
    ]
