# Generated by Django 5.1.3 on 2024-12-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_invoice', '0003_fuelinvoice_related_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelinvoice',
            name='related_year',
            field=models.IntegerField(default=2024, max_length=100),
        ),
    ]
