# Generated by Django 5.1.3 on 2024-11-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('token_number', models.CharField(max_length=100, unique=True)),
                ('vehicle_number', models.CharField(max_length=100)),
                ('running_chart_number', models.CharField(max_length=100, unique=True)),
                ('liters_pumped', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fuel_type', models.CharField(max_length=10)),
                ('fuel_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice_number', models.CharField(max_length=100)),
                ('deducted_running_chart_number', models.CharField(blank=True, max_length=100, null=True)),
                ('is_deducted', models.BooleanField(default=False)),
            ],
        ),
    ]
