# Generated by Django 5.1.3 on 2024-12-13 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_data', '0002_alter_fuelrecord_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelrecord',
            name='profit_per_litre',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
    ]
