# Generated by Django 5.1.3 on 2024-12-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_data', '0003_fuelrecord_profit_per_litre'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelrecord',
            name='transporter_name',
            field=models.CharField(default='buruwa', max_length=100),
            preserve_default=False,
        ),
    ]
